//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab01
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_DONHANG
    {
        public int IdDonHang { get; set; }
        public int IdSP { get; set; }
        public int SoLuong { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
